### ISSUE TITLE
Can the source be uploaded to the repository?

### ISSUE THREAD

**Issue by HeyItsLollie** [Great0ne/MGS1-PC-Randomizer#1]
First up, I just want to say thank you so much for making this. I've wanted to see a MGS1 randomizer for years, so it's great to finally have an option.

Is there any chance that your Lua & Assembly work could be uploaded to the repository as well? It'd be nice to see if anything can be done about the remaining issues. along with expanding the randomizer even further.

I could also see this randomizer being adapted for Archipelago (https://archipelago.gg/), I'm sure a ton of people would be excited to have MGS1 as an option.

**Comment by Great0ne** [comment]
Thanks, and yes I will upload the source code very soon, sorry about the lack of infos i'm working on other things at the moment, and I don't know much about archipelago but if the randomizer gets a clean version there is no limit.
